# -*- coding: utf-8 -*-
"""
Textos literais extraídos dos templates oficiais (item 15 e item 13)
para geração de ofícios de análise de recursos de filha maior solteira.
"""

# ============================================================================
# ITEM 15 - IMPROCEDENTE
# ============================================================================

ITEM15_ACHADOS = {
    "Apenas 1 filho": """A existência de filho em comum é critério objetivo de comprovação de união estável previsto na regulamentação do Sistema de Pessoal Civil (SIPEC). A Portaria SGP/SEDGG/ME nº 4.645/2022, ao disciplinar a instrução probatória, elenca como meios de prova: "certidão de nascimento de filho havido em comum; prova de mesmo domicílio; (…) quaisquer outros que possam levar à convicção do fato a comprovar" (art. 9º, itens exemplificativos). Assim, filho em comum, somado a mesmo endereço em cadastros oficiais (p. ex., Receita Federal, SIGEPE/CNIS) ou a registro no CadÚnico como cônjuge/companheira, constitui conjunto probatório robusto de união estável.""",

    "Mais de 1 filho": """A presença de mais de um filho em comum reforça a presunção de convivência estável e duradoura, afastando a hipótese de relação eventual. Tal situação evidencia a consolidação do núcleo familiar, em consonância com o art. 226, §3º da Constituição Federal, que reconhece a união estável como entidade familiar, e com o art. 1.723 do Código Civil, que a define como convivência pública, contínua e duradoura, estabelecida com o objetivo de constituição de família. O art. 1.724 do Código Civil estabelece ainda os deveres de sustento e educação dos filhos no âmbito da união estável, sendo a repetição do vínculo parental um indicativo objetivo de que tais deveres vêm sendo exercidos, o que reforça a estabilidade da convivência. A jurisprudência do Superior Tribunal de Justiça (REsp 1.055.265/RS; REsp 1.199.497/MG) reconhece que a existência de filhos em comum constitui forte elemento de prova da união estável, sobretudo quando associada a outros indícios de convivência pública e duradoura. No mesmo sentido, o Tribunal de Contas da União consolidou entendimento de que a existência de filho em comum descaracteriza a condição de filha maior solteira para fins de pensão prevista na Lei nº 3.373/1958 (Acórdão 7.972/2017 – 2ª Câmara). Se um único filho já é suficiente para afastar a condição, a existência de mais de um filho reforça ainda mais a evidência de união estável.""",

    "Filho + CadÚnico": """A existência de filho em comum é critério objetivo de comprovação de união estável previsto na regulamentação do Sistema de Pessoal Civil (SIPEC). A Portaria SGP/SEDGG/ME nº 4.645/2022, ao disciplinar a instrução probatória, elenca como meios de prova: "certidão de nascimento de filho havido em comum; prova de mesmo domicílio; (…) quaisquer outros que possam levar à convicção do fato a comprovar" (art. 9º, itens exemplificativos). Assim, filho em comum, somado a registro no CadÚnico como cônjuge/companheira, constitui conjunto probatório robusto de união estável.""",

    "Filho + Endereço em múltiplas bases": """A existência de filho em comum é critério objetivo de comprovação de união estável previsto na regulamentação do Sistema de Pessoal Civil (SIPEC). A Portaria SGP/SEDGG/ME nº 4.645/2022, ao disciplinar a instrução probatória, elenca como meios de prova: "certidão de nascimento de filho havido em comum; prova de mesmo domicílio; (…) quaisquer outros que possam levar à convicção do fato a comprovar" (art. 9º, itens exemplificativos). Assim, filho em comum, somado a mesmo endereço em cadastros oficiais (p. ex., Receita Federal, SIGEPE/CNIS, RENACH), constitui conjunto probatório robusto de união estável.""",

    "Endereço em múltiplas bases": """A divergência de endereço declinada pela Interessada não prevalece sobre a prova de coabitação extraída de cadastros oficiais (CNIS, Receita Federal, Sigepe, RENACH e histórico de prova de vida), os quais gozam de presunção de veracidade e fé pública (CF, art. 19, II). Nos autos, a coincidência de domicílio foi confirmada em múltiplas bases e, inclusive, apontada no extrato do indício do TCU, atendendo ao critério "prova de residência no mesmo domicílio" previsto no art. 9º, VI, da Portaria SGP/SEDGG/ME nº 4.645/2022.""",

    "Apenas CadÚnico": """Acerca da alegação de que os dados do CadÚnico estariam equivocados ou não poderiam ser considerados, registra-se que o Cadastro Único para Programas Sociais do Governo Federal, instituído pela Lei nº 8.742/1993 (art. 6º-F, com redação dada pela Lei nº 14.284/2021) e regulamentado pelo Decreto nº 11.016/2022, tem natureza declaratória, operando com informações prestadas diretamente pela própria família para fins de acesso a benefícios sociais. Dessa forma, a informação constante do CadÚnico configura verdadeira declaração formal perante a União, de modo que a indicação de vínculo de união estável/casamento no cadastro deve ser considerada elemento probatório relevante. Eventual erro somente poderia ser afastado mediante demonstração idônea de retificação realizada pelo próprio órgão gestor do CadÚnico, circunstância que não se verificou nos presentes autos.""",

    "Pensão INSS": """A Interessada reconhece ou não impugna o recebimento de pensão por morte do companheiro no âmbito do INSS, mas sustenta que tal fato não é suficiente para descaracterizar a condição de filha solteira. Conforme o Acórdão nº 7.972/2017 – 2ª Câmara/TCU (item 16), "jurisprudência pacificada no TCU determina que a filha solteira, para continuar recebendo a pensão instituída com essa fundamentação, não poderá ter contraído casamento e nem se encontrar em situação de união estável". Nesse mesmo julgado, o Tribunal assentou que beneficiárias de pensão por morte do companheiro no INSS não podem continuar recebendo pensão de filha maior solteira, pela contradição lógica entre as situações alegadas para a concessão dos benefícios. Assim, o recebimento de pensão do INSS na qualidade de companheira constitui elemento de prova suficiente da união estável e causa resolutiva plena do benefício previsto na Lei nº 3.373/1958."""
}

ITEM15_ARGUMENTOS = {
    "1": """A negativa de união estável apresentada não elide a prova documental constante nos autos, extraída de cadastros oficiais (CNIS, Receita Federal, Sigepe), dotados de fé pública (CF, art. 19, II). A jurisprudência pacificada do Tribunal de Contas da União (Acórdão nº 7.972/2017-2ªC) e os precedentes do Supremo Tribunal Federal (MS 38.515/2022 e MS 38.587/2023) reconhecem a união estável como causa resolutiva plena do benefício, não sendo suficiente a simples negativa da interessada para afastar os indícios confirmados.""",

    "2": """A existência de filho em comum é critério objetivo de comprovação de união estável previsto na regulamentação do Sistema de Pessoal Civil (SIPEC). A Portaria SGP/SEDGG/ME nº 4.645/2022, ao disciplinar a instrução probatória, elenca como meios de prova: "certidão de nascimento de filho havido em comum; prova de mesmo domicílio; (…) quaisquer outros que possam levar à convicção do fato a comprovar" (art. 9º, itens exemplificativos). Assim, filho em comum, somado a mesmo endereço em cadastros oficiais (p. ex., Receita Federal, SIGEPE/CNIS) ou a registro no CadÚnico como cônjuge/companheira, constitui conjunto probatório robusto de união estável.""",

    "3": """A presença de mais de um filho em comum reforça a presunção de convivência estável e duradoura, afastando a hipótese de relação eventual. Tal situação evidencia a consolidação do núcleo familiar, em consonância com o art. 226, §3º da Constituição Federal, que reconhece a união estável como entidade familiar, e com o art. 1.723 do Código Civil, que a define como convivência pública, contínua e duradoura, estabelecida com o objetivo de constituição de família. O art. 1.724 do Código Civil estabelece ainda os deveres de sustento e educação dos filhos no âmbito da união estável, sendo a repetição do vínculo parental um indicativo objetivo de que tais deveres vêm sendo exercidos, o que reforça a estabilidade da convivência. A jurisprudência do Superior Tribunal de Justiça (REsp 1.055.265/RS; REsp 1.199.497/MG) reconhece que a existência de filhos em comum constitui forte elemento de prova da união estável, sobretudo quando associada a outros indícios de convivência pública e duradoura. No mesmo sentido, o Tribunal de Contas da União consolidou entendimento de que a existência de filho em comum descaracteriza a condição de filha maior solteira para fins de pensão prevista na Lei nº 3.373/1958 (Acórdão 7.972/2017 – 2ª Câmara). Se um único filho já é suficiente para afastar a condição, a existência de mais de um filho reforça ainda mais a evidência de união estável.""",

    "4": """A divergência de endereço declinada pela Interessada não prevalece sobre a prova de coabitação extraída de cadastros oficiais (CNIS, Receita Federal, Sigepe e histórico de prova de vida), os quais gozam de presunção de veracidade e fé pública (CF, art. 19, II). Nos autos, a coincidência de domicílio foi confirmada em múltiplas bases e, inclusive, apontada no extrato do indício do TCU, atendendo ao critério "prova de residência no mesmo domicílio" previsto no art. 9º, VI, da Portaria SGP/SEDGG/ME nº 4.645/2022.""",

    "5": """Não foram apresentados documentos idôneos capazes de infirmar a presunção de veracidade dos registros oficiais. As manifestações trazidas não impugnam especificamente os fundamentos da decisão nem afastam as provas materiais constantes dos autos (cadastros oficiais e documentos públicos), razão pela qual permanece hígida a conclusão administrativa.""",

    "6": """Eventual decisão judicial pretérita que tenha versado sobre objeto diverso (v.g., dependência econômica) não obsta a presente apuração, cujo foco jurídico é a perda da condição de solteira por configuração de união estável — causa resolutiva plena do benefício de filha maior solteira. A jurisprudência do STF (MS 38.587/2023) registra a incompatibilidade entre a pensão de filha solteira e a união estável reconhecida, mencionando, inclusive, a determinação do TCU para revisão de benefícios (Acórdão 2.780/2016), o que afasta a existência de direito líquido e certo à manutenção da pensão em tais hipóteses.""",

    "7": """A dissolução posterior da união estável não restabelece o direito à pensão de filha maior solteira, por se tratar de condição resolutiva plena, conforme reconhecido pelo STF (MS 38.515/2022, Rel. Min. Dias Toffoli), que equipara os efeitos da união estável aos do casamento para fins de extinção do benefício previsto no art. 5º, parágrafo único, da Lei nº 3.373/1958.""",

    "8": """A mera intenção de judicializar não altera o enquadramento jurídico consolidado: a união estável é incompatível com a manutenção da pensão de filha maior solteira, consoante a orientação do TCU e os precedentes do STF (MS 38.515/2022 e MS 38.587/2023). Assim, os elementos probatórios constantes dos autos e a jurisprudência aplicável permanecem suficientes para a manutenção da decisão administrativa.""",

    "9": """A Interessada reconhece ou não impugna o recebimento de pensão por morte do companheiro no âmbito do INSS, mas sustenta que tal fato não é suficiente para descaracterizar a condição de filha solteira. Conforme o Acórdão nº 7.972/2017 – 2ª Câmara/TCU (item 16), "jurisprudência pacificada no TCU determina que a filha solteira, para continuar recebendo a pensão instituída com essa fundamentação, não poderá ter contraído casamento e nem se encontrar em situação de união estável". Nesse mesmo julgado, o Tribunal assentou que beneficiárias de pensão por morte do companheiro no INSS não podem continuar recebendo pensão de filha maior solteira, pela contradição lógica entre as situações alegadas para a concessão dos benefícios. Assim, o recebimento de pensão do INSS na qualidade de companheira constitui elemento de prova suficiente da união estável e causa resolutiva plena do benefício previsto na Lei nº 3.373/1958.""",

    "10": """As declarações de terceiros juntadas pela Interessada não possuem valor probante suficiente para afastar os indícios confirmados nos autos. Mera prova testemunhal, apresentada por escrito e sem a colheita sob o crivo do contraditório, não atende aos requisitos de validade processual e, portanto, tem eficácia limitada. A jurisprudência administrativa reconhece que a prova testemunhal não pode ser produzida unilateralmente por documentos particulares, devendo observar formalidades como ata notarial, que confere maior credibilidade e possibilita aferição das circunstâncias em que foram prestadas. Desse modo, tais declarações, desacompanhadas de outros elementos idôneos, não são aptas a infirmar a fé pública dos cadastros oficiais (CNIS, Receita Federal, Sigepe), dotados de presunção de veracidade (CF, art. 19, II).""",

    "11": """Acerca da alegação de que os dados do CadÚnico estariam equivocados ou não poderiam ser considerados, registra-se que o Cadastro Único para Programas Sociais do Governo Federal, instituído pela Lei nº 8.742/1993 (art. 6º-F, com redação dada pela Lei nº 14.284/2021) e regulamentado pelo Decreto nº 11.016/2022, tem natureza declaratória, operando com informações prestadas diretamente pela própria família para fins de acesso a benefícios sociais. Dessa forma, a informação constante do CadÚnico configura verdadeira declaração formal perante a União, de modo que a indicação de vínculo de união estável/casamento no cadastro deve ser considerada elemento probatório relevante. Eventual erro somente poderia ser afastado mediante demonstração idônea de retificação realizada pelo próprio órgão gestor do CadÚnico, circunstância que não se verificou nos presentes autos.""",

    "12": """A existência de filho em comum é critério objetivo de comprovação de união estável previsto na regulamentação do Sistema de Pessoal Civil (SIPEC). A Portaria SGP/SEDGG/ME nº 4.645/2022, ao disciplinar a instrução probatória, elenca como meios de prova: "certidão de nascimento de filho havido em comum; prova de mesmo domicílio; (…) quaisquer outros que possam levar à convicção do fato a comprovar" (art. 9º, itens exemplificativos). Assim, filho em comum, somado ao registro no CadÚnico como cônjuge/companheira, constitui conjunto probatório robusto de união estável."""
}

# ============================================================================
# ITEM 13 - PROCEDENTE
# ============================================================================

ITEM13_ACHADOS = {
    "Apenas 1 filho": """A negativa de união estável, acompanhada de documentação idônea constitui elemento suficiente para gerar dúvida razoável sobre a configuração de união estável, nos termos do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige ao menos dois documentos consistentes e convergentes. Ademais, a documentação apresentada pela Interessada vai de encontro ao conteúdo dos elementos detectados pelo Tribunal de Contas da União, suscitando dúvida quanto à sua suficiência como prova. Assim, a ausência de elementos robustos e convergentes em sentido contrário recomenda a manutenção do benefício.""",

    "Mais de 1 filho": """A negativa de união estável, acompanhada de documentação idônea constitui elemento suficiente para gerar dúvida razoável sobre a configuração de união estável, nos termos do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige ao menos dois documentos consistentes e convergentes. Ademais, a documentação apresentada pela Interessada vai de encontro ao conteúdo dos elementos detectados pelo Tribunal de Contas da União, suscitando dúvida quanto à sua suficiência como prova. Assim, a ausência de elementos robustos e convergentes em sentido contrário recomenda a manutenção do benefício.""",

    "Filho + CadÚnico": """O Cadastro Único, por força da Lei nº 8.742/1993 (art. 6º-F) e do Decreto nº 11.016/2022, possui natureza declaratória e é reconhecido como elemento de prova relevante, dotado de presunção de veracidade. Todavia, no presente caso, embora haja registro no CadÚnico, as alegações e documentos apresentados no recurso retiram a força probatória isolada do cadastro, gerando dúvida razoável sobre a configuração da união estável. Assim, a informação inicialmente apurada não se revela suficiente para descaracterizar a condição de filha maior solteira. Ressalva-se, entretanto, que o processo não impede eventual reabertura futura caso surjam novos elementos probatórios que venham a corroborar a declaração pretérita.""",

    "Filho + Endereço em múltiplas bases": """A negativa de união estável, acompanhada de documentação idônea constitui elemento suficiente para gerar dúvida razoável sobre a configuração de união estável, nos termos do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige ao menos dois documentos consistentes e convergentes. Ademais, a documentação apresentada pela Interessada vai de encontro ao conteúdo dos elementos detectados pelo Tribunal de Contas da União, suscitando dúvida quanto à sua suficiência como prova. Assim, a ausência de elementos robustos e convergentes em sentido contrário recomenda a manutenção do benefício.""",

    "Endereço em múltiplas bases": """A divergência de endereço declinada pela Interessada, acompanhada de documentação comprobatória, gera dúvida razoável sobre a configuração de união estável. Embora os cadastros oficiais gozem de presunção de veracidade, a ausência de convergência entre múltiplos elementos probatórios, conforme exigido pelo art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, recomenda a manutenção do benefício.""",

    "Apenas CadÚnico": """O Cadastro Único, por força da Lei nº 8.742/1993 (art. 6º-F) e do Decreto nº 11.016/2022, possui natureza declaratória e é reconhecido como elemento de prova relevante, dotado de presunção de veracidade. Todavia, no presente caso, embora haja registro no CadÚnico, as alegações e documentos apresentados no recurso retiram a força probatória isolada do cadastro, gerando dúvida razoável sobre a configuração da união estável. Assim, a informação inicialmente apurada não se revela suficiente para descaracterizar a condição de filha maior solteira. Ressalva-se, entretanto, que o processo não impede eventual reabertura futura caso surjam novos elementos probatórios que venham a corroborar a declaração pretérita.""",

    "Pensão INSS": """A negativa de união estável, acompanhada de documentação idônea constitui elemento suficiente para gerar dúvida razoável sobre a configuração de união estável, nos termos do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige ao menos dois documentos consistentes e convergentes. Ademais, a documentação apresentada pela Interessada vai de encontro ao conteúdo dos elementos detectados pelo Tribunal de Contas da União, suscitando dúvida quanto à sua suficiência como prova. Assim, a ausência de elementos robustos e convergentes em sentido contrário recomenda a manutenção do benefício."""
}

ITEM13_ARGUMENTOS = {
    "1": """A negativa de união estável, acompanhada de documentação idônea constitui elemento suficiente para gerar dúvida razoável sobre a configuração de união estável, nos termos do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige ao menos dois documentos consistentes e convergentes. Ademais, a documentação apresentada pela Interessada vai de encontro ao conteúdo dos elementos detectados pelo Tribunal de Contas da União, suscitando dúvida quanto à sua suficiência como prova. Assim, a ausência de elementos robustos e convergentes em sentido contrário recomenda a manutenção do benefício.""",

    "2": """A negativa de união estável, acompanhada de documentação idônea constitui elemento suficiente para gerar dúvida razoável sobre a configuração de união estável, nos termos do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige ao menos dois documentos consistentes e convergentes.""",

    "3": """A alegação de que a existência de múltiplos filhos não caracteriza união estável, acompanhada de documentação que gera dúvida razoável, recomenda a manutenção do benefício até que surjam elementos probatórios inequívocos.""",

    "4": """O registro constante do CadÚnico indicava vínculo de união estável da interessada, o que, em análise administrativa, verificou-se tratar-se de erro cadastral. Embora o CadÚnico, por sua natureza declaratória e presunção de veracidade, constitua elemento probatório relevante, a inconsistência identificada torna a informação inválida para fins de caracterização da união estável, anulando seu valor probatório no presente caso. Ademais, não foram localizados outros documentos idôneos capazes de corroborar o indício. À luz do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige a convergência de pelo menos dois elementos de prova consistentes, conclui-se que não há suporte suficiente para descaracterizar a condição de filha maior solteira.""",

    "5": """Não foram apresentados documentos oficiais que confirmem de forma inequívoca a união estável. A documentação juntada pela Interessada gera dúvida razoável quanto à configuração de união estável.""",

    "6": """A Interessada apresentou decisão judicial válida e eficaz que assegura a manutenção do benefício. Nos termos do art. 5º, XXXVI, da Constituição Federal, as decisões judiciais transitadas em julgado têm eficácia obrigatória e não podem ser revistas administrativamente. Assim, em respeito ao princípio da segurança jurídica e à autoridade da coisa julgada, deve ser preservada a manutenção do benefício até ulterior decisão judicial em contrário.""",

    "7": """A dissolução posterior da união estável, acompanhada de documentação que comprova o término do relacionamento, gera dúvida razoável sobre a manutenção da irregularidade.""",

    "8": """A intenção de judicializar, quando fundamentada em documentação robusta que gera dúvida razoável, recomenda a manutenção administrativa do benefício.""",

    "9": """O recebimento de pensão do INSS, quando acompanhado de documentação que esclarece as circunstâncias e gera dúvida sobre a união estável, não é suficiente isoladamente para descaracterizar a condição de filha solteira.""",

    "10": """As declarações de terceiros, quando acompanhadas de outros elementos que geram dúvida razoável, devem ser consideradas no conjunto probatório.""",

    "11": """O registro constante do CadÚnico indicava vínculo de união estável da interessada, o que, em análise administrativa, verificou-se tratar-se de erro cadastral. Embora o CadÚnico, por sua natureza declaratória e presunção de veracidade, constitua elemento probatório relevante, a inconsistência identificada torna a informação inválida para fins de caracterização da união estável, anulando seu valor probatório no presente caso. Ademais, não foram localizados outros documentos idôneos capazes de corroborar o indício. À luz do art. 9º da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige a convergência de pelo menos dois elementos de prova consistentes, conclui-se que não há suporte suficiente para descaracterizar a condição de filha maior solteira.""",

    "12": """A admissão da existência de filho em comum, quando acompanhada de negativa fundamentada de união estável e documentação que gera dúvida razoável, recomenda a manutenção do benefício."""
}

# ============================================================================
# TEXTO BASE DO ITEM 15 (Parágrafos 1-14)
# ============================================================================

ITEM15_PARAGRAFO_INICIAL = """Após a decisão administrativa acima mencionada, a Interessada foi regularmente notificada para apresentar recurso, o qual se encontra acostado ao processo e teve sua cópia juntada aos presentes autos eletrônicos. Em síntese, a peça recursal limita-se a negar a existência de união estável, apresentando documentos de caráter genérico e sem impugnar de forma específica os fundamentos expostos na decisão proferida neste processo. Assim, passa-se à análise pontual das alegações formuladas."""

ITEM15_CONCLUSAO = """Diante do exposto, como há, de fato, prova inequívoca, consubstanciada em documentação já anexada aos autos e nas informações constantes do extrato do TCU, de que a Interessada não permaneceu na condição de solteira — requisito indispensável à manutenção do recebimento da pensão temporária de filha maior solteira —, nos termos do parágrafo único do art. 5º da Lei nº 3.373/1958, da Portaria SGP/SEDGG/ME nº 4.645/2022, bem como da jurisprudência consolidada do TCU (Acórdão nº 7.972/2017-2ªC) e do Supremo Tribunal Federal (MS 38.515/2022 e MS 38.587/2023), conclui-se que o recurso não merece prosperar, devendo ser mantida a decisão que determinou a exclusão do benefício.

A defesa não apresentou elementos capazes de afastar a presunção de veracidade dos registros oficiais ou a aplicação da legislação pertinente (Lei nº 3.373/1958, art. 5º, parágrafo único; Portaria nº 4.645/2022, art. 9º).

A jurisprudência consolidada do TCU e do STF reafirma que a união estável equipara-se ao casamento para fins de extinção da pensão de filha maior solteira.

Dessa forma, resta confirmado o indício de irregularidade apontado pelo TCU, destacando-se que foram adotados os procedimentos necessários à apuração, em especial a observância aos princípios constitucionais do contraditório e ampla defesa e às orientações da Corte de Contas para apuração do indício."""

# ============================================================================
# TEXTO BASE DO ITEM 13 (Parágrafos 1-12)
# ============================================================================

ITEM13_PARAGRAFO_INICIAL = """Após a decisão administrativa acima mencionada, a Interessada foi regularmente notificada para apresentar recurso, o qual se encontra acostado ao processo e teve sua cópia juntada aos presentes autos eletrônicos. Em síntese, a peça recursal trouxe elementos que merecem apreciação, apresentando documentos e fundamentos que afastam, no caso concreto, os indícios inicialmente apontados. Assim, passa-se à análise das alegações formuladas, à luz das provas juntadas e do arcabouço normativo aplicável."""

ITEM13_CONCLUSAO = """Diante do exposto, verifica-se que não há prova inequívoca nos autos capaz de demonstrar que a Interessada deixou de preencher o requisito de filha maior solteira, a documentação apresentada no mínimo, inviabiliza a conclusão pela existência de união estável. indispensável à manutenção do recebimento da pensão temporária, prevista no parágrafo único do art. 5º da Lei nº 3.373/1958.

O indício inicialmente apontado pelo Tribunal de Contas da União não foi corroborado por elementos suficientes a caracterizar a união estável, nos termos da Portaria SGP/SEDGG/ME nº 4.645/2022, que exige, em seu art. 9º, a apresentação de pelo menos dois documentos probatórios idôneos. Ao contrário, a Interessada trouxe aos autos documentação atualizada (v.g., certidão de estado civil, declarações de imposto de renda sem companheiro, comprovantes de residência distintos), além de argumentos jurídicos relevantes, aptos a suscitar dúvida razoável quanto à configuração de união estável.

A jurisprudência do Tribunal de Contas da União (Acórdão nº 7.972/2017-2ªC) e do Supremo Tribunal Federal (MS 38.515/2022 e MS 38.587/2023) reconhece que a união estável constitui causa resolutiva plena da pensão. Todavia, no presente caso, não restou comprovada sua ocorrência de forma inequívoca, razão pela qual se impõe a reforma da decisão anterior em respeito aos princípios constitucionais da ampla defesa, do contraditório e da segurança jurídica.

Dessa forma, não se confirma o indício de irregularidade apontado pelo TCU, destacando-se que foram adotados os procedimentos necessários à apuração, e que a dúvida remanescente deve ser interpretada em favor da manutenção do benefício, em consonância com a jurisprudência administrativa e judicial aplicável.

Ressalva-se, entretanto, que o processo não impede eventual reabertura futura caso surjam novos elementos probatórios que venham a corroborar a declaração pretérita."""
